(function(){
'use strict';
var FILL_KEY='shq_fill_v1',STATE_KEY='shq_after_sale_v1';
var GOOGLE='https://maps.app.goo.gl/5cVXhw1VefmqZtwW6';
var YELP='https://www.yelp.com/biz/sheehy-nissan-of-manassas-manassas-2';
var fill=load(FILL_KEY,{}),saved=load(STATE_KEY,{progress:{}}),selected=saved.selected||'delivery';
function $(id){return document.getElementById(id);}function load(k,fb){try{return JSON.parse(localStorage.getItem(k)||'null')||fb;}catch(e){return fb;}}function save(k,v){try{localStorage.setItem(k,JSON.stringify(v));}catch(e){}}
function esc(s){return String(s==null?'':s).replace(/[&<>"']/g,function(c){return {'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c];});}
function fv(k,fb){var e=document.querySelector('[data-f="'+k+'"]'),v=e&&e.value?e.value.trim():'';return v||fb;}function N(){return fv('name','[Name]');}function V(){return fv('vehicle','[vehicle]');}function A(){return fv('agent','[agent]');}function P(){return fv('number','[number]');}
function purchase(){return $('purchaseType').value;}function issue(){return $('issueState').value;}function survey(){return $('surveyState').value;}function cue(){return ($('personalCue').value||'').trim();}
function caseKey(){return [N(),V(),$('deliveryDate').value||'no-date'].join('|');}function caseProgress(){saved.progress=saved.progress||{};saved.progress[caseKey()]=saved.progress[caseKey()]||{};return saved.progress[caseKey()];}
function done(id){return !!caseProgress()[id];}function setDone(id,v){caseProgress()[id]=!!v;saveState();}
function saveState(){saved.deliveryDate=$('deliveryDate').value;saved.purchaseType=purchase();saved.issueState=issue();saved.surveyState=survey();saved.selected=selected;save(STATE_KEY,saved);}
function dateAt(day){if(!$('deliveryDate').value)return null;var d=new Date($('deliveryDate').value+'T12:00:00');d.setDate(d.getDate()+day);return d;}function daysSince(){if(!$('deliveryDate').value)return null;var d=new Date($('deliveryDate').value+'T12:00:00'),now=new Date();now.setHours(12,0,0,0);return Math.floor((now-d)/86400000);}function fmt(d){return d?d.toLocaleDateString('en-US',{month:'short',day:'numeric',year:d.getFullYear()!==new Date().getFullYear()?'numeric':undefined}):'Add delivery date';}
function cp(text,btn){function ok(){var o=btn.textContent;btn.textContent='Copied';setTimeout(function(){btn.textContent=o;},850);}if(navigator.clipboard&&navigator.clipboard.writeText)navigator.clipboard.writeText(text).then(ok).catch(function(){fallback(text);ok();});else{fallback(text);ok();}}function fallback(t){var a=document.createElement('textarea');a.value=t;a.style.position='fixed';a.style.opacity='0';document.body.appendChild(a);a.select();try{document.execCommand('copy');}catch(e){}a.remove();}
function commonCue(){return cue()?'Personal cue: '+cue()+'. ':'';}
var M=[
{id:'delivery',day:0,label:'Delivery day',title:'First-night check',channels:['sms','email'],goal:'Make the handoff feel personal and catch an immediate problem before it becomes frustration.'},
{id:'day1',day:1,label:'Day 1',title:'24-hour ownership call',channels:['call','vm','sms'],goal:'Listen to the first real ownership impression and clean up anything still unclear.'},
{id:'day3',day:3,label:'Day 3',title:'Experience cleanup',channels:['sms','email'],goal:'Surface anything unfinished in features, paperwork, condition or the overall buying experience.'},
{id:'note',day:7,label:'Day 7',title:'Handwritten thank-you',channels:['mail'],goal:'Create a personal touch that has nothing to do with a survey, review or referral.'},
{id:'survey',day:10,label:'Day 10',title:'Nissan survey check',channels:['call','vm','sms','email'],goal:'Help a new-Nissan buyer recognize the purchase survey and surface any unresolved issue without coaching a score.',newOnly:true},
{id:'google',day:14,label:'Day 14',title:'Google experience review',channels:['sms','email'],goal:'Ask every customer on the standard cadence for a genuine Google review with no rating request and no incentive.'},
{id:'referral',day:30,label:'Day 30',title:'Referral conversation',channels:['call','vm','sms','email'],goal:'Ask confidently for an introduction after you have delivered a month of ownership support.'},
{id:'gift',day:45,label:'Day 45',title:'Surprise and delight',channels:['gift','mail'],goal:'Send an optional personal appreciation touch that is independent of survey, review and referral activity.',optional:true},
{id:'ownership90',day:90,label:'Day 90',title:'90-day ownership check',channels:['call','vm','sms'],goal:'Stay useful after the transaction and learn what the customer actually thinks after the new-car glow fades.'},
{id:'sixmonth',day:180,label:'6 months',title:'Relationship check',channels:['call','sms','email'],goal:'Stay top of mind as an automotive resource without manufacturing a sales reason.'},
{id:'anniversary',day:365,label:'1 year',title:'Ownership anniversary',channels:['sms','mail'],goal:'Mark the relationship, not just the transaction.'}
];
function visibleMilestones(){return M.filter(function(m){return !m.newOnly||purchase()==='new-nissan';});}function milestone(id){return M.filter(function(m){return m.id===id;})[0]||M[0];}
function scriptsFor(id){var n=N(),v=V(),a=A(),p=P(),newN=purchase()==='new-nissan';
if(issue()==='open')return {title:'Issue recovery first',goal:'Own the problem before asking for anything else.',channels:['call','vm','sms','email'],call:'Hi '+n+', '+a+' at Sheehy Nissan. I saw that we still have something open on your '+v+'. I am not calling about a survey or review. I want to get the actual issue clear first. Walk me through exactly what is still unresolved and I will take the next step from there.',vm:'Hi '+n+', '+a+' at Sheehy Nissan. I am following up on the open item with your '+v+'. I want to get the issue clear and make sure it reaches the right person. Call or text me at '+p+'.',sms:'Hi '+n+', '+a+' at Sheehy Nissan. I want to get the open item on your '+v+' handled before anything else. What is the one part that is still unresolved?',subject:'[Name], Let’s Get the Open Item on Your [vehicle] Handled'.replace('[Name]',n).replace('[vehicle]',v),email:'Hi '+n+',\n\nI want to get the open item on your '+v+' handled before anything else. I am not reaching out about a survey, review or referral.\n\nTell me the one part that is still unresolved and I will work the correct next step.\n\n'+a};
if(id==='delivery')return {title:'First-night check',goal:milestone(id).goal,channels:['sms','email'],sms:'Hi '+n+', '+a+' here. You have had the '+v+' for a few hours now. First impression: what do you love already and is there anything you want me to clear up tonight?',subject:'🔑 '+n+', First Night With the '+v,email:'Hi '+n+',\n\nYou have had a little time with the '+v+' now, so I wanted to check the handoff while everything is still fresh.\n\nWhat do you love already and is there anything you want me to clear up tonight?\n\n'+a};
if(id==='day1')return {title:'24-hour ownership call',goal:milestone(id).goal,channels:['call','vm','sms'],call:'Hi '+n+', it is '+a+' at Sheehy Nissan. You have had your first real day with the '+v+'. Give me the quick read: what is better than expected and what still needs an explanation?',vm:'Hi '+n+', '+a+' at Sheehy Nissan. I wanted to catch you after your first real day with the '+v+' and make sure the vehicle and handoff are landing the way they should. Call or text me at '+p+'.',sms:'Hi '+n+', first real day with the '+v+'. What is better than expected and what still needs an explanation? I want to get anything unclear handled while it is fresh.'};
if(id==='day3')return {title:'Experience cleanup',goal:milestone(id).goal,channels:['sms','email'],sms:'Hi '+n+', you should be settling into the '+v+' now. Anything with the features, controls, paperwork or delivery that still feels unfinished? Tell me now and I will help get it handled.',subject:'🔎 '+n+', Anything Still Unfinished on the '+v,email:'Hi '+n+',\n\nYou have had a few days with the '+v+' now. I want to make sure the purchase feels finished, not just that the paperwork is finished.\n\nIs there anything with the features, controls, paperwork or delivery that still needs attention? Tell me the one thing and I will work it.\n\n'+a};
if(id==='note')return {title:'Handwritten thank-you',goal:milestone(id).goal,channels:['mail'],mail:n+',\n\nThank you for trusting me with your '+v+'. I hope it makes everyday life a little easier and more enjoyable. If you ever need help with the vehicle or just need a straight automotive answer, call me.\n\nI appreciate your business.\n\n'+a,internal:commonCue()+'Handwrite this. If the customer gave you a real personal detail, reference it naturally in one sentence. Do not mention a survey, review or referral.'};
if(id==='survey')return {title:'Nissan survey check',goal:milestone(id).goal,channels:['call','vm','sms','email'],call:survey()==='completed'?'Hi '+n+', '+a+' at Sheehy Nissan. Thank you for taking the time to complete Nissan\'s survey. I am not calling to ask what you scored. I just want to make sure the '+v+' and the ownership experience are still where they should be. Anything you need from me?':'Hi '+n+', '+a+' at Sheehy Nissan. Has Nissan\'s purchase survey reached you yet? If it has, please answer it based on your real experience. More importantly, is there anything from the purchase, delivery or vehicle setup that I still need to fix or explain?',vm:'Hi '+n+', '+a+' at Sheehy Nissan. I am checking on you and the '+v+'. Nissan may also have sent a purchase survey. I mainly want to make sure nothing from your purchase or delivery still needs attention. Call or text me at '+p+'.',sms:survey()==='completed'?'Hi '+n+', thank you for completing Nissan\'s survey. I do not need the score. I just want to make sure the '+v+' and everything around the purchase are still good on your end. Anything you need from me?':'Hi '+n+', quick check on the '+v+'. Has Nissan\'s purchase survey reached you yet? If it has, please answer it based on your experience. Anything from the purchase or delivery I still need to help with?',subject:'⭐ '+n+', Quick Ownership Check on the '+v,email:survey()==='completed'?'Hi '+n+',\n\nThank you for taking the time to complete Nissan\'s survey. I am not asking what you scored. I just want to make sure the '+v+' and everything around the purchase are still where they should be.\n\nAnything you need from me?\n\n'+a:'Hi '+n+',\n\nI wanted to check on you and the '+v+'. Nissan may have sent a short purchase survey. If it reached you, please answer it based on your real experience.\n\nMore importantly, is there anything from the purchase, delivery, paperwork or vehicle setup that I still need to help with?\n\n'+a};
if(id==='google')return {title:'Google experience review',goal:milestone(id).goal,channels:['sms','email'],sms:'Hi '+n+', now that you have had real time with the '+v+', I would value your honest take on working with us. If you have a minute, here is our Google page: '+GOOGLE+' A genuine review about your experience helps other shoppers know what to expect.',subject:'⭐ '+n+', Your Honest Take on the Experience',email:'Hi '+n+',\n\nNow that you have had real time with the '+v+', I would value your honest take on working with us.\n\nIf you have a minute, you can share your experience on Google here:\n'+GOOGLE+'\n\nNo need to write a novel. A genuine review helps other shoppers know what to expect.\n\nThank you again,\n'+a,internal:'Use the same standard cadence for customers. Do not ask for a particular rating, do not offer anything for the review and do not connect this ask to a gift.'};
if(id==='referral')return {title:'Referral conversation',goal:milestone(id).goal,channels:['call','vm','sms','email'],call:'Hi '+n+', you have had the '+v+' about a month now and I wanted to ask you one direct favor. If I earned your trust, the best compliment you can give me is an introduction. Who comes to mind first that may need a vehicle next? You do not have to sell them. Just connect us and I will take care of the rest.',vm:'Hi '+n+', '+a+' at Sheehy Nissan. I wanted to check on the '+v+' and ask you one quick favor when you have a second. Call or text me at '+p+'.',sms:'Quick favor, '+n+'. If I earned your trust, who comes to mind that may need a vehicle next? You do not have to sell me. Just introduce us and I will take care of the rest.',subject:'👋 '+n+', One Favor After a Month With the '+v,email:'Hi '+n+',\n\nYou have had the '+v+' about a month now. If I earned your trust, the best compliment you can give me is an introduction.\n\nWho comes to mind that may need a vehicle next? You do not have to sell them on me. Just connect us and I will take care of the rest.\n\n'+a};
if(id==='gift')return {title:'Surprise and delight',goal:milestone(id).goal,channels:['gift','mail'],gift:commonCue()+'Choose something small and personal based on something the customer actually told you, not on survey score, review activity or referral activity. Confirm dealership policy before purchasing or mailing anything.',mail:'Saw this and thought of you, '+n+'. I hope the '+v+' is treating you well. Thanks again for trusting me.\n\n'+a,internal:'Do not mention a survey, Google, Yelp or a referral in the gift note. The gift stands on its own.'};
if(id==='ownership90')return {title:'90-day ownership check',goal:milestone(id).goal,channels:['call','vm','sms'],call:'Hi '+n+', you have had the '+v+' long enough for the new-car glow to wear off. I want the real ownership answer now. What is one thing you love and one thing you would change?',vm:'Hi '+n+', '+a+' at Sheehy Nissan. I am checking in at about the 90-day mark on the '+v+'. I would love the real ownership read when you have a minute. Call or text me at '+p+'.',sms:'About 90 days with the '+v+' now. Give me the real ownership read: one thing you love and one thing you would change?' };
if(id==='sixmonth')return {title:'Six-month relationship check',goal:milestone(id).goal,channels:['call','sms','email'],call:'Hi '+n+', '+a+' at Sheehy Nissan. I am not calling to sell you another car six months later. I am checking whether there is anything automotive I can make easier for you right now, whether it is the '+v+', service direction or just a question.',sms:'Hi '+n+', six-month check from '+a+'. Anything automotive I can make easier for you right now with the '+v+' or otherwise?',subject:'🔑 '+n+', Six Months With the '+v,email:'Hi '+n+',\n\nSix months with the '+v+' already. I am not reaching out to manufacture a sales reason. I just want to stay useful.\n\nAnything automotive I can make easier for you right now with the vehicle, ownership or a question you have?\n\n'+a};
return {title:'Ownership anniversary',goal:milestone('anniversary').goal,channels:['sms','mail'],sms:'One year already, '+n+'. I hope the '+v+' has been good to you. Thanks again for trusting me with it. If you need anything automotive this year, you know who to call. '+a,mail:n+',\n\nOne year with the '+v+' already. Thank you again for trusting me with the purchase. I hope it has served you well and made life a little easier.\n\nIf you need anything automotive this year, I am still your person.\n\n'+a};
}
function channelName(c){return {call:'Call',vm:'Voicemail',sms:'SMS',email:'Email',mail:'Post mail',gift:'Gift'}[c]||c;}function card(kind,title,text,subject){if(!text)return '';return '<div class="script-card '+kind+'"><div class="head"><b>'+esc(title)+'</b><button class="copy-btn" type="button">Copy</button></div>'+(subject?'<div class="subject">'+esc(subject)+'</div>':'')+'<div class="body">'+esc(text)+'</div></div>';}
function renderTimeline(){var host=$('timeline'),age=daysSince(),p=caseProgress(),list=visibleMilestones();host.innerHTML='';list.forEach(function(m){var d=dateAt(m.day),isDone=!!p[m.id],cls='timeline-card'+(isDone?' complete':m.optional?' optional':age!=null&&age>=m.day?' due':age!=null&&m.day-age<=7?' upcoming':'');var el=document.createElement('div');el.className=cls;el.innerHTML='<div class="timeline-top"><div><div class="timeline-day">'+esc(m.label)+'</div><h3>'+esc(m.title)+'</h3></div><span class="pill '+(isDone?'good':age!=null&&age>=m.day?'warn':'blue')+'">'+(isDone?'Done':age!=null&&age>=m.day?'Due':'Planned')+'</span></div><p>'+esc(m.goal)+'</p><div class="timeline-date">'+esc(fmt(d))+'</div><div class="timeline-actions"><button class="mini-btn primary open" type="button">Open</button><button class="mini-btn '+(isDone?'done':'')+' toggle" type="button">'+(isDone?'Undo':'Done')+'</button></div>';el.querySelector('.open').onclick=function(){selected=m.id;saveState();renderWorkspace();};el.querySelector('.toggle').onclick=function(){setDone(m.id,!done(m.id));renderAll();};host.appendChild(el);});}
function nextMilestone(){if(issue()==='open')return {id:'recovery',title:'Resolve the open ownership issue',goal:'Call the customer and own the unresolved item before any survey, review, referral or gift ask.'};var age=daysSince();if(age==null)return null;var list=visibleMilestones();for(var i=0;i<list.length;i++)if(age>=list[i].day&&!done(list[i].id))return list[i];for(var j=0;j<list.length;j++)if(!done(list[j].id))return list[j];return null;}
function renderNow(){var n=nextMilestone(),age=daysSince(),meta=$('nowMeta');meta.innerHTML='';if(!n){$('nextMove').textContent=$('deliveryDate').value?'Ownership cadence complete for the current timeline.':'Add a delivery date to start the ownership timeline.';$('nextSub').textContent='';return;}$('nextMove').textContent=n.title;$('nextSub').textContent=n.goal||'';var bits=[];if(age!=null)bits.push(age===0?'Delivery day':age+' days owned');bits.push(purchase()==='new-nissan'?'New Nissan':'Used / non-Nissan');bits.push(issue()==='open'?'Open issue':'No open issue');bits.forEach(function(t){var s=document.createElement('span');s.className='pill';s.textContent=t;meta.appendChild(s);});if(n.id!=='recovery'){selected=n.id;saveState();}}
function renderKpi(){var show=purchase()==='new-nissan';$('kpiPanel').style.display=show?'block':'none';$('surveyState').closest('label').style.display=show?'block':'none';if(show){var txt=survey()==='completed'?'Survey completed':survey()==='arrived'?'Survey received':'Survey not established';$('surveyBadge').textContent=txt;}}
function renderWorkspace(){var s=scriptsFor(selected),host=$('scripts');$('workTitle').textContent=s.title;$('workGoal').textContent=s.goal||'';$('channelRow').innerHTML=(s.channels||[]).map(function(c){return '<span class="channel-tag '+c+'">'+esc(channelName(c))+'</span>';}).join('');var html='';if(s.call)html+=card('call','Call',s.call);if(s.vm)html+=card('vm','Voicemail',s.vm);if(s.sms)html+=card('sms','SMS',s.sms);if(s.email)html+=card('email','Email',s.email,s.subject);if(s.mail)html+=card('mail','Handwritten / post mail',s.mail);if(s.gift)html+=card('gift','Gift direction',s.gift);if(s.internal)html+=card('gift','Internal note',s.internal);host.innerHTML=html;host.querySelectorAll('.script-card').forEach(function(c){var b=c.querySelector('.copy-btn'),body=(c.querySelector('.body')||{}).textContent||'',sub=(c.querySelector('.subject')||{}).textContent||'';b.onclick=function(){cp((sub?'Subject: '+sub+'\n\n':'')+body,b);};});$('markDone').style.display=selected==='recovery'?'none':'inline-flex';$('markDone').textContent=done(selected)?'Marked done':'Mark done';$('quickLinks').style.display=issue()==='open'?'none':'flex';var y=$('quickLinks').querySelector('.yelp');if(y)y.title='Yelp listing only. Do not solicit a Yelp review.';}
function renderIssue(){$('issueBanner').classList.toggle('on',issue()==='open');}
function renderAll(){renderKpi();renderIssue();renderTimeline();renderNow();renderWorkspace();saveState();}
function seed(){document.querySelectorAll('[data-f]').forEach(function(el){var k=el.getAttribute('data-f');el.value=fill[k]||'';el.addEventListener('input',function(){fill[k]=el.value;save(FILL_KEY,fill);renderAll();});});$('deliveryDate').value=saved.deliveryDate||'';$('purchaseType').value=saved.purchaseType||'new-nissan';$('issueState').value=saved.issueState||'clear';$('surveyState').value=saved.surveyState||'unknown';$('personalCue').value='';['deliveryDate','purchaseType','issueState','surveyState'].forEach(function(id){$(id).addEventListener('change',function(){if(id==='purchaseType'&&purchase()!=='new-nissan'&&selected==='survey')selected='day3';renderAll();});});$('personalCue').addEventListener('input',renderWorkspace);$('markDone').onclick=function(){setDone(selected,true);renderAll();};$('clearCase').onclick=function(){['name','vehicle'].forEach(function(k){fill[k]='';var e=document.querySelector('[data-f="'+k+'"]');if(e)e.value='';});save(FILL_KEY,fill);$('deliveryDate').value='';$('purchaseType').value='new-nissan';$('issueState').value='clear';$('surveyState').value='unknown';$('personalCue').value='';selected='delivery';saved.deliveryDate='';saved.selected=selected;saveState();renderAll();};}
seed();renderAll();
})();
