(function(){
'use strict';
var $=function(id){return document.getElementById(id);};
var PROFILE_KEY='shq_fill_v1';
function val(id){var e=$(id);return e&&e.value?String(e.value).trim():'';}
function profile(){try{return JSON.parse(localStorage.getItem(PROFILE_KEY)||'{}')||{};}catch(e){return {};}}
function phone(){return profile().number||'703-996-9877';}
function name(){return val('clientName')||'there';}
function car(){return val('vehicle')||'the vehicle';}
function need(){return val('customerNeed')||'';}
function concern(){return val('concern')||'';}
function useCase(){return val('useCase')||'';}
function condition(){return val('condition')||'';}
function comparison(){return val('comparison')||'';}
function travel(){return val('travel')||'';}
function t1(){return val('timeOne')||'later today';}
function t2(){return val('timeTwo')||'tomorrow';}
function proofs(){return ['proof1','proof2','proof3'].map(val).filter(Boolean);}
function sentence(s){s=String(s||'').trim();if(!s)return '';return /[.!?]$/.test(s)?s:s+'.';}
function esc(s){return String(s==null?'':s).replace(/[&<>"']/g,function(c){return {'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c];});}
function proofSpeech(list){var lead=['First, take a look at ','Next, look at ','And I want you to see '];return list.map(function(x,i){var y=String(x).replace(/^show\s+/i,'').replace(/[.!?]+$/,'').trim();return lead[Math.min(i,2)]+y+'.';}).join(' ');}
function appointmentClose(){return 'If this looks like the right one, I can have it ready '+t1()+' or '+t2()+'. Which works better?';}
function conditionClose(){return 'From what I showed you, does the condition look acceptable? If it does, the next question is whether the numbers make sense.';}
function answerClose(){return 'Does that answer the question, or is there one more thing you need verified before we take the next step?';}
function comparisonClose(){return 'If you’re comparing it to another one, send me the listing, stock number or written offer and I’ll tell you the meaningful differences.';}
function remoteClose(){return 'If this checks the boxes, the next step is to structure the deal so you know exactly where you stand before you make the trip.';}
function tradeClose(){return 'If the vehicle works for you, send me the VIN and current mileage on your trade and I’ll get that side started.';}
function chosenClose(def){var x=val('nextCommitment');if(x==='appointment')return appointmentClose();if(x==='condition')return conditionClose();if(x==='answer')return answerClose();if(x==='comparison')return comparisonClose();if(x==='remote')return remoteClose();if(x==='trade')return tradeClose();return def;}
function intro(){return 'Hi '+name()+', Aldrin at Sheehy Nissan. This is the actual '+car()+'.';}
function focusLine(){if(need()&&useCase())return 'You told me '+need()+' matters for '+useCase()+', so that’s where I’m starting.';if(need())return 'You told me '+need()+' matters, so that’s where I’m starting.';if(useCase())return 'You told me you’re using it for '+useCase()+', so I’m keeping this focused on that.';return 'I’m going to keep this focused on the few things that actually affect your decision.';}
function materialLine(prefix){return condition()?sentence((prefix||'One thing I also want you to see clearly is ')+condition()):'';}
function situ(){return val('situation')||'first';}
var DATA={
first:{title:'First response · actual vehicle',length:'55–70 sec',goal:'Earn the appointment',objective:'Prove this is the actual vehicle, connect 2–3 details to the customer’s stated priority, then ask for a specific visit time.',script:function(){return [intro(),focusLine(),proofSpeech(proofs()),materialLine(),chosenClose(appointmentClose())].filter(Boolean).join('\n\n');},shots:[['0–8s','Face + exact unit','Say the customer’s name and identify the exact vehicle.'],['8–20s','Strongest visual reason','Start with the exterior, color, trim or feature that matters most.'],['20–40s','2–3 relevant proof points','Only show equipment tied to the customer’s use or stated priority.'],['40–52s','Interior / condition proof','Show the condition or interior area most likely to affect the decision.'],['52–65s','Face + close','Ask for the next commitment; do not end with “let me know.”']],avoid:['Do not read the window sticker or list every feature.','Do not say “perfect,” “flawless,” or “like new” unless that is exceptionally supportable.','Do not finish with a vague question. Give the customer a concrete next step.']},
feature:{title:'Feature / configuration proof',length:'40–65 sec',goal:'Answer the exact question',objective:'Put the requested feature first, show it operating or physically present, then confirm whether anything else is a hard requirement.',script:function(){var q=concern()?'You asked specifically about '+concern()+', so I’m starting there.':'You had a specific equipment question, so I’m starting with the exact item that matters.';return [intro(),q,proofSpeech(proofs()),materialLine('The one difference or condition point I want you to see is '),chosenClose(answerClose())].filter(Boolean).join('\n\n');},shots:[['0–7s','Exact vehicle','Identify the unit; no lot tour.'],['7–20s','Requested feature first','Do not make them wait 60 seconds to see what they asked about.'],['20–38s','Function / proof','Show how it works or where it is equipped.'],['38–50s','Supporting feature','Show only another item that materially supports the same buying need.'],['50–60s','Decision question','Confirm whether the question is solved before you ask for an appointment.']],avoid:['Do not bury the requested feature behind a generic walk-around.','Do not claim equipment you have not verified on this exact vehicle.','Do not turn one feature question into a 90-second brochure recital.']},
used:{title:'Used-vehicle condition proof',length:'75–100 sec',goal:'Build condition confidence',objective:'Show what the customer is actually buying: exterior, tires, interior, mileage/condition and any material imperfection before you sell features.',script:function(){var m=condition()?'I noticed '+condition()+', and I want you to see it clearly before you make a decision.':'I’m starting with condition because on a used vehicle that matters more than a long feature list.';return [intro(),m,proofSpeech(proofs()),'I’m showing you the actual car so you can judge the condition for yourself.',chosenClose(conditionClose())].filter(Boolean).join('\n\n');},shots:[['0–8s','Exact unit + odometer context','Identify the vehicle and mileage if verified/useful.'],['8–28s','Exterior / imperfections','Walk the body slowly enough to see paint, glass and any visible damage.'],['28–42s','Wheels + tires','Show wheel faces and tread visually; do not guess tread depth.'],['42–68s','Seats + dash','Show driver bolster, passenger area, dash and startup/warning-light context.'],['68–86s','Rear / cargo / headliner','Show the areas used-car buyers cannot judge from listing photos.'],['86–100s','Close on condition','Ask whether the condition is acceptable before moving to numbers.']],avoid:['Do not hide the flaw and hope they miss it in person.','Do not minimize damage with “you can barely see it.”','Do not estimate tire depth, reconditioning or mechanical condition unless verified.']},
damage:{title:'Damage / imperfection close-up',length:'35–55 sec',goal:'Get a condition decision',objective:'Show the imperfection from enough angles that the customer can decide whether it is acceptable.',script:function(){var issue=condition()||concern()||'the condition point you asked about';return [intro(),'You asked about '+issue+', so I want to show it clearly instead of describing it from memory.','I’m starting farther back so you can see where it is, then I’ll move closer and change the angle so you can judge the size and reflection for yourself.',proofSpeech(proofs()),chosenClose('Based on what you can see here, is that acceptable to you, or is it a deal-breaker?')].filter(Boolean).join('\n\n');},shots:[['0–7s','Locate it','Show the panel or area from a normal viewing distance.'],['7–18s','Move closer','Give the customer a clear close-up.'],['18–30s','Change angle','Use reflection/light so dents, scratches or paint variation can be judged.'],['30–40s','Show scale','Include an adjacent body line, hand or other natural reference.'],['40–50s','State what you know','Describe it; do not minimize it.'],['50–55s','Ask for a decision','Is the condition acceptable or not?']],avoid:['Do not call a visible defect “nothing.”','Do not promise repair unless it is authorized.','Do not use a flattering camera angle to hide the condition.']},
remote:{title:'Remote buyer · proof before travel',length:'90–120 sec',goal:'Reduce uncertainty before commitment',objective:'Give enough visual proof that a distance buyer can decide whether to structure the deal without making a blind trip.',script:function(){var loc=travel()?'Since you’re coming from '+travel()+', I want to answer the big questions before you leave home.':'Since you’re not local, I want to answer the big questions before I ask you to travel.';return [intro(),loc,focusLine(),proofSpeech(proofs()),materialLine(),chosenClose(remoteClose())].filter(Boolean).join('\n\n');},shots:[['0–10s','Exact unit / stock proof','Identify the actual vehicle clearly.'],['10–28s','Full exterior sweep','Body, glass, wheels and requested color/configuration.'],['28–45s','Close-ups of condition','Show imperfections, tire/wheel condition and anything likely to create a surprise.'],['45–65s','Startup + dash','Vehicle on, odometer and dash; show warning-light context accurately.'],['65–88s','Seats / interior / headliner','Driver bolster, rear seating, infotainment and requested equipment.'],['88–105s','Cargo / utility','Show the space the customer said matters.'],['105–120s','Remote next step','Move toward deal structure, not an unnecessary exploratory trip.']],avoid:['Do not ask a distant customer to travel just to learn basic facts you can verify now.','Do not call something “clean” if you have not inspected the areas they asked about.','Do not promise long-distance dealership delivery or unverified transport terms.']},
price:{title:'Price shopper · value comparison',length:'55–80 sec',goal:'Earn an apples-to-apples comparison',objective:'Give concrete reasons to compare this exact vehicle and obtain the competing listing or written offer.',script:function(){var other=comparison()?'You’re comparing this against '+comparison()+', so I want to make sure we’re comparing the same thing.':'If you’re shopping the number, I want to make sure the comparison is actually apples to apples.';return [intro(),other,'I’m not going to read you a feature list. I’m showing the specific things that affect value on this vehicle.',proofSpeech(proofs()),materialLine(),chosenClose(comparisonClose())].filter(Boolean).join('\n\n');},shots:[['0–8s','Exact vehicle','Make clear which trim/unit is being compared.'],['8–24s','Condition + mileage context','Show actual condition and mileage if verified.'],['24–42s','Equipment that affects value','Only options/trim differences that matter in the comparison.'],['42–55s','Tires / color / notable value point','Concrete value, not “best deal” language.'],['55–70s','Comparison close','Ask for the other listing, stock number or written offer.']],avoid:['Do not claim “best price” or “best deal” without support.','Do not discount the car in the video. First establish whether the competing vehicle is truly comparable.','Do not use features the customer does not value as a substitute for a price answer.']},
family:{title:'Family space / comfort / utility',length:'60–85 sec',goal:'Prove everyday fit',objective:'Show the seating, access, cargo and comfort points the customer will actually live with.',script:function(){return [intro(),focusLine(),proofSpeech(proofs()),materialLine(),chosenClose('Based on what I showed you, does the space and layout solve what you need, or is there one area you want me to show closer before we set a time?')].filter(Boolean).join('\n\n');},shots:[['0–8s','Exact vehicle','Start outside, then move immediately to the space question.'],['8–25s','Rear-seat access','Door opening, second row and third row when relevant.'],['25–42s','Passenger comfort','Legroom, vents, charging and seat layout only if relevant.'],['42–58s','Cargo','Show usable cargo with the seat configuration they care about.'],['58–70s','Driver view / cameras','Only if this was part of their stated priority.'],['70–82s','Close the fit question','Ask whether the layout solves the stated use case.']],avoid:['Do not assume children, family size or lifestyle details the customer did not tell you.','Do not list every USB port and safety feature unless it affects their stated need.','Do not call driver-assistance technology autonomous.']},
truck:{title:'Truck / SUV capability',length:'65–90 sec',goal:'Prove the use case',objective:'Show the bed, cab, drivetrain/capability equipment and condition tied to how the customer will use the vehicle.',script:function(){return [intro(),focusLine(),'On a truck or utility vehicle, I’d rather show the capability points than spend the video on cosmetics.',proofSpeech(proofs()),materialLine(),chosenClose('Does this look like it fits the job you need it to do, or is there one capability point you want me to verify before we set the next step?')].filter(Boolean).join('\n\n');},shots:[['0–8s','Exact truck / SUV','Identify cab, trim and drivetrain only if verified.'],['8–25s','Bed / cargo / utility','Bed liner, tie-downs, outlets, cargo area or hitch when relevant.'],['25–42s','Tires / stance / 4x4 equipment','Show what is actually equipped.'],['42–58s','Cab / rear seat','Space and configuration.'],['58–72s','Camera / controls','Only equipment tied to towing, parking or off-road use.'],['72–88s','Close the capability question','Ask what still needs verification.']],avoid:['Do not quote towing or payload from memory when exact configuration matters.','Do not imply capability beyond the equipment actually present.','Do not spend most of the video on appearance when the customer asked about utility.']},
performance:{title:'Luxury / performance vehicle',length:'65–90 sec',goal:'Build certainty in condition + equipment',objective:'Show the details that justify attention on a higher-value or performance vehicle, then let the drive become the next proof point.',script:function(){return [intro(),'On this kind of vehicle, condition and equipment matter more than a long walk-around, so I’m going straight to those.',proofSpeech(proofs()),materialLine(),chosenClose('If the condition and equipment check out from here, the drive is what decides it. I can have it ready '+t1()+' or '+t2()+'. Which works better?')].filter(Boolean).join('\n\n');},shots:[['0–8s','Exterior identity','Exact trim, stance and visible condition.'],['8–24s','Wheels / brakes / tires','Show condition and performance equipment only when verified.'],['24–42s','Driver area','Seats, wheel, gauges, drive-mode controls and key equipment.'],['42–58s','Startup / sound','Only if useful and appropriate.'],['58–72s','Material condition','Show wear or flaws that matter on this type of vehicle.'],['72–88s','Appointment close','The drive becomes the next proof point.']],avoid:['Do not make performance claims you have not verified.','Do not hide wheel, tire or seat wear where condition heavily affects value.','Do not use hype where concrete equipment and condition sell better.']},
ev:{title:'EV / hybrid ownership fit',length:'65–90 sec',goal:'Prove ownership fit',objective:'Show verified charging, range/efficiency, cargo and daily-use facts that matter to the customer’s routine.',script:function(){return [intro(),focusLine(),'I’m only going to show the ownership points I’ve verified on this exact vehicle.',proofSpeech(proofs()),materialLine(),chosenClose('If those pieces fit your routine, what—if anything—do you still need answered about charging, range or ownership before we take the next step?')].filter(Boolean).join('\n\n');},shots:[['0–8s','Exact vehicle','Identify trim/drivetrain accurately.'],['8–24s','Charging / fuel-system proof','Connector/charge port or hybrid-specific interface when relevant.'],['24–42s','Verified range / efficiency display','Only show verified vehicle/manufacturer information.'],['42–58s','Cabin / drive controls','Modes, displays and equipment the customer will actually use.'],['58–72s','Cargo / packaging','Show any space impact that matters.'],['72–88s','Ownership question','Surface the remaining charging/range/use-case concern.']],avoid:['Do not promise real-world range from memory.','Do not state incentives unless current eligibility is verified.','Do not overload the customer with terminology that does not affect their use case.']},
compare:{title:'Comparable / alternative vehicle',length:'55–80 sec',goal:'Test whether the alternative deserves attention',objective:'Disclose the meaningful difference immediately, prove the platform or need, then ask whether the difference is acceptable.',script:function(){var diff=condition()?'The meaningful difference is '+condition()+'.':'This is not the exact vehicle you first asked about, so I want to be clear about that up front.';return [intro(),diff,focusLine(),proofSpeech(proofs()),chosenClose('If this solves the reason you wanted the original vehicle, what else would still have to be right before you would consider moving forward?')].filter(Boolean).join('\n\n');},shots:[['0–8s','Name the difference first','Do not let the customer discover the mismatch halfway through the video.'],['8–24s','Prove the shared need','Seating, ride, layout, feature or condition point they actually care about.'],['24–42s','Show the meaningful difference','Color, trim, year or equipment difference.'],['42–58s','Supporting proof','Only details that help them judge whether the compromise works.'],['58–72s','Decision close','Ask whether the alternative solves the reason they wanted the original.']],avoid:['Do not present a comparable as identical.','Do not expose another store location unnecessarily; use shared-inventory language when applicable.','Do not promise an off-site/shared unit can be moved before the required commitment and management approval.']}
};
function currentData(){return DATA[situ()]||DATA.first;}
function defaultCloseFor(s){if(s==='used'||s==='damage')return 'condition';if(s==='remote')return 'remote';if(s==='price')return 'comparison';if(s==='feature'||s==='ev')return 'answer';return 'appointment';}
function subjectLine(){var s=situ();if(s==='price')return car()+' — the comparison that matters';if(s==='used'||s==='damage')return car()+' — condition video';if(s==='remote')return car()+' — proof before the trip';if(s==='feature')return car()+' — the feature you asked about';if(s==='compare')return car()+' — the meaningful differences';return car()+' — quick video';}
function focal(){if(need())return need();if(concern())return concern();if(condition())return condition();return 'the part that matters most to your decision';}
function sms(){var s=situ();if(s==='price')return 'Hi '+name()+', Aldrin at Sheehy Nissan. I sent the video on the '+car()+' showing the points that matter in an apples-to-apples comparison. If you have the other listing or offer, send it to me and I’ll compare the meaningful differences.';if(s==='used'||s==='damage')return 'Hi '+name()+', Aldrin at Sheehy Nissan. I sent the condition video on the '+car()+'. The main thing I wanted you to see was '+focal()+'. From what I showed you, is that condition acceptable?';if(s==='remote')return 'Hi '+name()+', Aldrin at Sheehy Nissan. I sent a proof video of the actual '+car()+' focused on '+focal()+'. If it checks the boxes, the next step is to structure the deal before you travel.';if(s==='feature')return 'Hi '+name()+', Aldrin at Sheehy Nissan. I sent the video answering '+(concern()||'the equipment question')+' on the actual '+car()+'. Does that answer it, or is there one more must-have I should verify?';if(s==='compare')return 'Hi '+name()+', Aldrin at Sheehy Nissan. I sent the comparable '+car()+' video and called out the meaningful difference. Does it still solve the reason you wanted the original, or is that difference a hard line?';return 'Hi '+name()+', Aldrin at Sheehy Nissan. I sent the actual '+car()+' video and focused on '+focal()+'. Based on what you told me, does that look like the right fit?';}
function email(){var s=situ(),body='Hi '+name()+',\n\n';if(s==='price')body+='I sent the DriveCentric video on the actual '+car()+' so you can compare the vehicle—not just two advertised numbers. I focused on the equipment, condition and value points that matter in a real comparison.\n\nIf you have the other listing, stock number or written offer, send it over and I’ll tell you the meaningful differences.';else if(s==='used'||s==='damage')body+='I sent the condition video on the actual '+car()+'. I made sure to show '+focal()+' clearly so you can judge it before spending time on the next step.\n\nFrom what I showed you, does the condition look acceptable?';else if(s==='remote')body+='I sent a more complete video of the actual '+car()+' because I want the big questions answered before you travel. I focused on '+focal()+'.\n\nIf the vehicle checks the boxes, the next step is to structure the deal so you know exactly where you stand before making the trip.';else if(s==='feature')body+='I sent the video on the actual '+car()+' and started with '+(concern()||'the feature you asked about')+'.\n\nDoes that answer it, or is there one more must-have you want me to verify?';else if(s==='compare')body+='I sent the comparable '+car()+' video and called out the meaningful difference instead of pretending it is the same vehicle.\n\nIf it solves the reason you wanted the original, tell me what—if anything—still has to be right before you would consider moving forward.';else body+='I sent a short video of the actual '+car()+' and focused on '+focal()+'.\n\nBased on what you told me, does that look like the right fit? If it does, I have '+t1()+' or '+t2()+' available.';return {subject:subjectLine(),body:body};}
function voicemail(){var s=situ();if(s==='remote')return 'Hi '+name()+', this is Aldrin at Sheehy Nissan. I just sent you a proof video of the actual '+car()+' so you can judge it before making the trip. Take a look when you can. If it checks out, call or text me at '+phone()+' and we’ll work the deal structure next.';if(s==='price')return 'Hi '+name()+', this is Aldrin at Sheehy Nissan. I just sent you a short video of the '+car()+' showing the points that matter in a real comparison. If you have the other listing or offer, send it over or call me at '+phone()+'.';if(s==='used'||s==='damage')return 'Hi '+name()+', this is Aldrin at Sheehy Nissan. I sent you the condition video on the '+car()+', including the area you asked about. Take a look and call or text me at '+phone()+' if the condition works for you.';return 'Hi '+name()+', this is Aldrin at Sheehy Nissan. I just sent you a short video of the actual '+car()+' focused on '+focal()+'. Take a look when you can. If it checks the box, call or text me at '+phone()+'.';}
function crm(){var p=proofs(),cta=val('nextCommitment')==='auto'?defaultCloseFor(situ()):val('nextCommitment');return 'DriveCentric video sent on '+car()+'. Situation: '+currentData().title+'. Focus: '+focal()+'.'+(p.length?' Proof shown: '+p.join('; ')+'.':'')+(condition()?' Material condition/difference: '+condition()+'.':'')+' CTA: '+cta+'.';}
function shotHtml(x){return '<div class="shot"><div class="shot-time">'+esc(x[0])+'</div><div><b>'+esc(x[1])+'</b><span>'+esc(x[2])+'</span></div></div>';}
function avoidHtml(x){return '<div class="avoid-line"><b>Don’t:</b> '+esc(x.replace(/^Do not\s*/i,''))+'</div>';}
function fallback(text){var ta=document.createElement('textarea');ta.value=text;ta.style.position='fixed';ta.style.opacity='0';document.body.appendChild(ta);ta.select();try{document.execCommand('copy');}catch(e){}ta.remove();}
function copied(btn){var old=btn.textContent;btn.textContent='Copied';setTimeout(function(){btn.textContent=old;},850);var t=$('toast');t.classList.add('show');setTimeout(function(){t.classList.remove('show');},700);}
function copyText(text,btn){if(navigator.clipboard&&navigator.clipboard.writeText)navigator.clipboard.writeText(text).then(function(){copied(btn);}).catch(function(){fallback(text);copied(btn);});else{fallback(text);copied(btn);}}
function channelCard(nameText,meta,text,subject){var id='c_'+Math.random().toString(36).slice(2),sub=subject?'<span class="subject">Subject: '+esc(subject)+'</span>':'';return '<div class="channel"><div class="channel-head"><div><div class="channel-name">'+esc(nameText)+'</div><div class="channel-meta">'+esc(meta)+'</div></div><button class="copy" type="button" data-copy="'+id+'">Copy</button></div><div class="channel-body" id="'+id+'">'+sub+esc(text)+'</div></div>';}
function renderChannels(){var em=email();$('channels').innerHTML=channelCard('SMS','Use only when texting is permitted',sms())+channelCard('Email','No manual signature — your system adds it',em.body,em.subject)+channelCard('Voicemail','Keep it under roughly 20–25 seconds',voicemail())+channelCard('CRM note','Factual record of what was actually sent',crm());document.querySelectorAll('[data-copy]').forEach(function(b){b.onclick=function(){var el=$(b.getAttribute('data-copy'));copyText(el.innerText||el.textContent||'',b);};});}
var REPLIES={
good:{label:'Looks good',line:function(){return situ()==='remote'?'Good. Then let’s structure the deal so you know exactly where you stand before you travel. Are you planning to finance it or pay cash?':'Good. Then let’s put a time on it. I have '+t1()+' or '+t2()+'. Which works better?';},after:'Do not re-sell the vehicle after a positive answer. Move directly to the missing commitment.'},
price:{label:'Price problem',line:function(){return 'It sounds like the number is the part that still has to make sense. Compared with what—another exact vehicle, a written offer, or the target you had in mind?';},after:'Mirror the actual number or comparison. Then isolate: “Other than price, what else would stop you?”'},
condition:{label:'Condition concern',line:function(){return 'Which condition point is the problem for you?';},after:'Get specific. Do not defend the vehicle until you know whether the issue is cosmetic, repair-related, or a true deal-breaker.'},
feature:{label:'Missing feature',line:function(){return 'Which feature is the hard line for you?';},after:'Once the must-have is clear, verify whether this exact unit has it. If not, change the vehicle—not the customer’s requirement.'},
think:{label:'Needs to think',line:function(){return 'It sounds like one part is still unsettled. What is the one thing you need to get comfortable with before this becomes a yes or no?';},after:'Let them answer. Mirror the key phrase, isolate it, solve that issue, then re-close.'},
compare:{label:'Comparing another car',line:function(){return 'Send me the other listing, stock number or written offer. What looks better to you right now—the selling price, equipment, condition, trade, or convenience?';},after:'Compare the exact variables instead of negotiating against an undefined competitor.'},
more:{label:'Wants more info',line:function(){return 'Absolutely. What is the one detail that could actually change your decision?';},after:'Answer that detail first. Do not respond with another generic feature dump.'},
noresponse:{label:'No response',line:function(){return 'I sent the walk-around. The main thing I wanted you to see was '+focal()+'. Based on what you told me, does that look like the right fit?';},after:'Do not ask “Did you watch it?” Give them the reason to reopen the video and one easy question to answer.'}
};
var activeReply='good';
function renderReplies(){$('replyButtons').innerHTML=Object.keys(REPLIES).map(function(k){return '<button type="button" data-reply="'+k+'" class="'+(k===activeReply?'on':'')+'">'+esc(REPLIES[k].label)+'</button>';}).join('');var r=REPLIES[activeReply]||REPLIES.good;$('nextLine').textContent=r.line();$('nextAfter').textContent=r.after;document.querySelectorAll('[data-reply]').forEach(function(b){b.onclick=function(){activeReply=b.getAttribute('data-reply');renderReplies();};});}
function renderMissing(){var x=[];if(!val('vehicle'))x.push('Add the exact vehicle.');if(!need()&&!concern()&&situ()!=='used'&&situ()!=='damage')x.push('Add what matters or the exact question so the video does not become generic.');if((situ()==='damage'||situ()==='used')&&!condition()&&!concern())x.push('Add the condition point you inspected.');if(situ()==='price'&&!comparison())x.push('If you know the competing vehicle or offer, add it; otherwise the script will ask for it.');var el=$('missing');if(x.length){el.textContent=x.join(' ');el.classList.add('show');}else{el.textContent='';el.classList.remove('show');}}
function render(){var d=currentData();$('situationTitle').textContent=d.title;$('lengthBadge').textContent=d.length;$('goalBadge').textContent=d.goal;$('objectiveText').textContent=d.objective;$('spokenScript').textContent=d.script();$('shotList').innerHTML=d.shots.map(shotHtml).join('');$('avoidList').innerHTML=d.avoid.map(avoidHtml).join('');renderChannels();renderReplies();renderMissing();}
function bind(){['clientName','vehicle','situation','customerNeed','concern','useCase','proof1','proof2','proof3','condition','comparison','travel','nextCommitment','timeOne','timeTwo'].forEach(function(id){var e=$(id);if(!e)return;e.addEventListener('input',render);e.addEventListener('change',render);});$('refreshBtn').onclick=render;$('clearVideo').onclick=function(){['customerNeed','concern','useCase','proof1','proof2','proof3','condition','comparison','travel'].forEach(function(id){$(id).value='';});$('nextCommitment').value='auto';render();};setTimeout(render,80);}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',bind);else bind();
})();