(function(){
'use strict';
var $=function(id){return document.getElementById(id);};
var PROFILE_KEY='shq_fill_v1';
function val(id){var e=$(id);return e&&e.value?String(e.value).trim():'';}
function profile(){try{return JSON.parse(localStorage.getItem(PROFILE_KEY)||'{}')||{};}catch(e){return {};}}
function phone(){return profile().number||'703-996-9877';}
function name(){return val('clientName')||'there';}
function car(){return val('vehicle')||'the vehicle';}
function phrase(){return val('customerPhrase');}
function need(){return val('customerNeed');}
function concern(){return val('concern');}
function useCase(){return val('useCase');}
function condition(){return val('condition');}
function comparison(){return val('comparison');}
function travel(){return val('travel');}
function t1(){return val('timeOne')||'later today';}
function t2(){return val('timeTwo')||'tomorrow';}
function situ(){return val('situation')||'first';}
function proofs(){return ['proof1','proof2','proof3'].map(val).filter(Boolean);}
function esc(s){return String(s==null?'':s).replace(/[&<>"']/g,function(c){return {'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c];});}
function cleanPhrase(s){return String(s||'').replace(/[\r\n]+/g,' ').replace(/\s+/g,' ').trim();}
function sentence(s){s=String(s||'').trim();if(!s)return '';return /[.!?]$/.test(s)?s:s+'.';}
function score(id){var n=parseInt(val(id),10);return isNaN(n)?0:n;}
function scoreOptions(){var h='<option value="">Not scored</option>';for(var i=1;i<=10;i++)h+='<option value="'+i+'">'+i+(i===1?' · very low':i===5?' · uncertain':i===10?' · strong':'')+'</option>';return h;}
function certaintyGap(){var a=[{k:'vehicle',label:'Vehicle',n:score('certaintyVehicle')},{k:'you',label:'You / trust',n:score('certaintyYou')},{k:'store',label:'Store / process',n:score('certaintyStore')}].filter(function(x){return x.n>0;});if(!a.length)return null;a.sort(function(x,y){return x.n-y.n;});return a[0];}
function certStrong(){var vals=[score('certaintyVehicle'),score('certaintyYou'),score('certaintyStore')].filter(Boolean);return vals.length>0&&vals.every(function(x){return x>=8;});}
function certaintyTarget(){var g=certaintyGap();if(!g)return 'Not scored';return g.label+' · '+g.n+'/10';}
function certaintyInstruction(){var g=certaintyGap();if(!g)return 'Use the video to learn what is still uncertain. Do not assume the gap.';if(g.n>=8)return 'The scored certainties are strong. Ask for the next commitment and stop presenting.';if(g.k==='vehicle')return 'Vehicle certainty is lowest. Put the exact fit, feature or condition proof first.';if(g.k==='you')return 'Trust in you is lowest. Be precise, use their words and show exactly what you are seeing.';return 'Store/process certainty is lowest. Remove the surprise: show the actual unit and make the next step clear.';}
function deliveryStyle(){return val('deliveryStyle')||'neutral';}
function deliveryText(){var s=deliveryStyle();if(s==='direct')return 'Match brisk pace · short sentences · firm close';if(s==='warm')return 'Warm start · use name naturally · let them finish';if(s==='formal')return 'Measured · precise · respectful';if(s==='analytical')return 'Factual · slower pace · prove the comparison';return 'Positive voice · match pace · slow on key proof';}
function languageTarget(){var p=cleanPhrase(phrase());return p?'Echo: “'+p+'”':'Listen for their exact words';}
function focusLine(){var p=cleanPhrase(phrase());if(p)return 'You said, “'+p+'.” So I’m going straight to that.';if(need()&&useCase())return 'You told me '+need()+' matters for '+useCase()+', so that is where I’m starting.';if(need())return 'You told me '+need()+' matters, so that is where I’m starting.';if(concern())return 'You asked about '+concern()+', so I’m starting there.';if(useCase())return 'You told me you are using it for '+useCase()+', so I’m keeping this focused on that.';return 'I’m going to keep this to the few things that can actually change your decision.';}
function proofSpeech(list){if(!list.length)return '';var lead=['First, take a look at ','Next, look at ','And I want you to see '];return list.map(function(x,i){var y=String(x).replace(/^show\s+/i,'').replace(/[.!?]+$/,'').trim();return y?lead[Math.min(i,2)]+y+'.':'';}).filter(Boolean).join(' ');}
function materialLine(prefix){return condition()?sentence((prefix||'One thing I also want you to see clearly is ')+condition()):'';}
function summaryLine(){var p=cleanPhrase(phrase());if(p)return 'So the standard you gave me was, “'+p+'.” That is what I wanted to prove here.';if(need()&&concern())return 'So the '+need()+' has to work, and '+concern()+' was the question. That is what I wanted to prove here.';if(need())return 'So '+need()+' is the part that has to be right. That is what I wanted to prove here.';if(concern())return 'So the question was '+concern()+'. That is what I wanted to answer here.';return '';}
function intro(){return 'Hi '+name()+', Aldrin at Sheehy Nissan. I have the actual '+car()+' in front of me.';}
function appointmentClose(){return 'If that checks the box, I can have it ready '+t1()+' or '+t2()+'. Which works better?';}
function conditionClose(){return 'Based on what you can see here, is the condition acceptable to you?';}
function answerClose(){return 'Does that answer the question, or is there one more thing you need verified?';}
function comparisonClose(){return 'Send me the other listing, stock number or written offer. I’ll compare the parts that actually affect the deal.';}
function remoteClose(){return 'If the vehicle itself checks out from here, the next step is to structure the deal so you know exactly where you stand before you travel.';}
function tradeClose(){return 'If the vehicle works for you, send me the VIN and current mileage on your trade and I’ll get that side started.';}
function uncertaintyClose(){return 'What, if anything, is still missing before this feels like the right next step?';}
function chosenClose(def){var x=val('nextCommitment');if(x==='appointment')return appointmentClose();if(x==='condition')return conditionClose();if(x==='answer')return answerClose();if(x==='comparison')return comparisonClose();if(x==='remote')return remoteClose();if(x==='trade')return tradeClose();if(!certStrong()&&certaintyGap()&&certaintyGap().n<8)return uncertaintyClose();return def;}
function script(parts){return parts.filter(Boolean).join('\n\n');}
function closeSilence(){return '[Ask the question. Stop. Let them answer.]';}
var DATA={
first:{title:'First response · actual vehicle',length:'50–70 sec',goal:'Build vehicle certainty',objective:'Use the customer’s own language, prove 2–3 relevant points on the actual unit and earn the next commitment.',script:function(){return script([intro(),focusLine(),proofSpeech(proofs()),materialLine(),summaryLine(),chosenClose(appointmentClose()),closeSilence()]);},shots:[['0–7s','Face + exact unit','Say their name once, identify the exact vehicle and begin with a little more vocal energy than normal conversation.'],['7–20s','Their reason first','Show the feature, condition point or visual tied to the words they used.'],['20–40s','2–3 proof points','Translate features into their use. Do not list equipment they did not ask about.'],['40–52s','Decision-changing detail','Show the material difference, imperfection or missing item now.'],['52–65s','Summary + close','Summarize what they said matters, ask one next-step question, then stop.']],avoid:['Match their pace before trying to lead it.','Use their exact noun or phrase once when it helps them feel understood.','Do not bury the close under another feature after you ask the question.']},
feature:{title:'Feature / configuration proof',length:'35–55 sec',goal:'Answer the exact question',objective:'Put the requested feature first, prove it on the actual vehicle and find out whether anything else is a hard requirement.',script:function(){var q=concern()?'You asked specifically about '+concern()+'.':'You had a specific equipment question.';return script([intro(),focusLine(),q,proofSpeech(proofs()),materialLine('The one other detail I want you to see is '),summaryLine(),chosenClose(answerClose()),closeSilence()]);},shots:[['0–6s','Exact vehicle','Identify the unit and move immediately to the requested item.'],['6–22s','Requested feature','Show it physically present or operating. Do not make them wait through an exterior tour.'],['22–36s','Supporting proof','Show one or two related points only if they help answer the same need.'],['36–48s','Summary','Repeat the requirement in the customer’s language.'],['48–55s','Decision question','Ask whether the question is solved, then pause.']],avoid:['Do not convert one feature question into a brochure recital.','If they use a specific term for the feature, reuse it rather than replacing it with dealership jargon.','Do not ask for an appointment before you answer the question they actually asked.']},
used:{title:'Used-vehicle condition proof',length:'70–100 sec',goal:'Build condition certainty',objective:'Let the customer judge the actual condition, including the parts most likely to create a surprise later.',script:function(){var m=condition()?'I noticed '+condition()+', and I want you to see it clearly.':'On a used vehicle, condition is the first thing I want you to be able to judge for yourself.';return script([intro(),focusLine(),m,proofSpeech(proofs()),summaryLine(),chosenClose(conditionClose()),closeSilence()]);},shots:[['0–8s','Exact unit + mileage context','Identify the vehicle and odometer when useful and verified.'],['8–30s','Exterior + imperfections','Walk body, glass and visible flaws slowly enough to judge.'],['30–45s','Wheels + tires','Show wheel faces and tread visually.'],['45–70s','Seats + dash','Driver bolster, passenger area, dash and startup context.'],['70–88s','Rear / cargo / headliner','Show areas listing photos often miss.'],['88–100s','Condition decision','Ask whether the condition works for them, then stop.']],avoid:['Do not minimize a visible defect. Show it from a normal distance and close-up.','Do not fill silence after the condition question by defending the car.','If condition is the weakest certainty, solve condition before discussing a discount.']},
damage:{title:'Damage / imperfection close-up',length:'30–50 sec',goal:'Get a condition decision',objective:'Show the exact imperfection from enough angles that the customer can decide whether it is acceptable.',script:function(){var issue=condition()||concern()||'the area you asked about';return script([intro(),'You asked about '+issue+', so I’m showing that first instead of describing it from memory.','I’ll show it from normal viewing distance, then close-up and from another angle.',proofSpeech(proofs()),summaryLine(),chosenClose(conditionClose()),closeSilence()]);},shots:[['0–6s','Locate it','Show where the issue sits on the vehicle.'],['6–18s','Normal distance','Let them judge how visible it is from a realistic viewing distance.'],['18–30s','Close-up','Show the actual mark, dent, chip or wear.'],['30–40s','Change angle','Use light/reflection so the surface can be judged.'],['40–50s','Ask for decision','Do not minimize it. Ask whether it works for them.']],avoid:['Do not call a visible defect “nothing.”','Do not choose an angle that makes the defect disappear.','After you ask whether the condition is acceptable, stay quiet.']},
remote:{title:'Remote buyer · proof before travel',length:'85–120 sec',goal:'Reduce uncertainty before commitment',objective:'Answer the big visual questions before the customer spends hours traveling, then move toward remote deal structure.',script:function(){var loc=travel()?'Since you’re coming from '+travel()+', I want to remove the big question marks before you leave home.':'Since you’re not local, I want to remove the big question marks before I ask you to travel.';return script([intro(),loc,focusLine(),proofSpeech(proofs()),materialLine(),summaryLine(),chosenClose(remoteClose()),closeSilence()]);},shots:[['0–10s','Exact unit','Make it obvious this is the actual vehicle.'],['10–30s','Exterior sweep','Body, glass, wheels, color/configuration and requested visual details.'],['30–48s','Condition close-ups','Anything that could feel different in person goes on camera now.'],['48–68s','Startup + dash','Odometer and relevant dash information when verified.'],['68–92s','Seats / equipment','Show the items tied to their stated use and concern.'],['92–108s','Cargo / utility','Show usable space if it matters.'],['108–120s','Summary + remote next step','Confirm the vehicle question, then move to deal structure.']],avoid:['A distance buyer needs more proof, not a harder appointment pitch.','Use the customer’s exact concern in the first 20 seconds so they know this video is for them.','Once the vehicle is strong enough, move to numbers/structure instead of asking them to drive for answers you can provide remotely.']},
price:{title:'Price shopper · value comparison',length:'50–75 sec',goal:'Create a real comparison',objective:'Show the exact unit and obtain the competing listing or offer before you negotiate against an undefined number.',script:function(){var other=comparison()?'You’re comparing this against '+comparison()+'.':'It sounds like the number is the first part you want clear.';return script([intro(),other,focusLine(),'I want the comparison to be the same vehicle, equipment and condition - not just two advertised numbers.',proofSpeech(proofs()),materialLine(),summaryLine(),chosenClose(comparisonClose()),closeSilence()]);},shots:[['0–8s','Exact unit','Make the trim/configuration clear.'],['8–25s','Condition + mileage','Show the pieces that materially affect value.'],['25–42s','Equipment difference','Only the options that change the comparison.'],['42–55s','One value proof','Show a concrete difference, not a generic claim.'],['55–70s','Get the comparison','Ask for the listing/offer and stop negotiating against yourself.']],avoid:['Do not defend the price before you know what they are comparing it to.','A calibrated question should expose the comparison, not dodge a factual price question.','If price is the only gap, isolate it before involving the desk.']},
family:{title:'Family space / comfort / utility',length:'55–80 sec',goal:'Prove everyday fit',objective:'Show the seating, access, cargo and comfort points tied to the customer’s actual use.',script:function(){return script([intro(),focusLine(),proofSpeech(proofs()),materialLine(),summaryLine(),chosenClose('Does the space and layout solve what you need, or is there one area you want me to show closer?'),closeSilence()]);},shots:[['0–7s','Exact vehicle','Move quickly to the use case.'],['7–24s','Rear-seat access','Second/third row access only if it matters to their situation.'],['24–42s','Comfort + layout','Legroom, seat layout, vents/charging when relevant.'],['42–58s','Cargo','Show actual usable space in the configuration they care about.'],['58–70s','Driver view','Only if visibility/technology is part of the decision.'],['70–80s','Fit question','Ask whether the layout solves the need.']],avoid:['Do not assume family details they did not tell you.','Echo their own use-case words instead of inventing a lifestyle story.','When they say the layout works, move forward; do not continue selling space.']},
truck:{title:'Truck / SUV capability',length:'60–90 sec',goal:'Prove the job',objective:'Show the exact capability/equipment tied to the customer’s intended use and identify what still needs verification.',script:function(){return script([intro(),focusLine(),'I’m going to stay on the capability points that matter to what you need this vehicle to do.',proofSpeech(proofs()),materialLine(),summaryLine(),chosenClose('Does this cover the job you need it to do, or is there one capability point I still need to verify?'),closeSilence()]);},shots:[['0–8s','Exact configuration','Cab, trim and drivetrain when verified.'],['8–26s','Bed / cargo / utility','Bed liner, tie-downs, hitch/outlets or cargo system when relevant.'],['26–43s','4x4 / equipment','Show actual controls/equipment without guessing specs.'],['43–60s','Cab / seating','The interior configuration tied to the use case.'],['60–76s','Camera / controls','Only relevant capability tech.'],['76–88s','Capability question','Ask what still needs proof.']],avoid:['Do not quote towing/payload from memory.','Match the customer’s use-case language instead of giving a generic truck speech.','If a capability fact is still uncertain, verify it rather than filling the gap with confidence theater.']},
performance:{title:'Luxury / performance vehicle',length:'60–85 sec',goal:'Build product certainty',objective:'Use concrete condition/equipment proof to build desire and let the drive become the next decisive experience.',script:function(){return script([intro(),focusLine(),'On this kind of vehicle, the details matter more than a long feature list, so I’m going straight to the ones that change the experience.',proofSpeech(proofs()),materialLine(),summaryLine(),chosenClose('If the condition and equipment check out from here, the drive is the next proof. I can have it ready '+t1()+' or '+t2()+'. Which works better?'),closeSilence()]);},shots:[['0–8s','Exterior identity','Exact trim, stance and visible condition.'],['8–24s','Wheels / brakes / tires','Show condition and verified equipment.'],['24–42s','Driver environment','Seats, wheel, gauges, controls and material quality.'],['42–55s','Startup / sound','Only when useful and appropriate.'],['55–70s','Material condition','Wear/flaws that matter at this value point.'],['70–82s','Drive close','Let the drive become the next proof point.']],avoid:['Use certainty in your voice, not exaggerated adjectives.','Match enthusiasm to the customer instead of performing at them.','Ask for the drive once the product certainty is strong; do not keep feature-dumping.']},
ev:{title:'EV / hybrid ownership fit',length:'60–85 sec',goal:'Build ownership certainty',objective:'Show the verified charging/range/efficiency and daily-use facts tied to the customer’s routine.',script:function(){return script([intro(),focusLine(),'I’m only going to show the ownership points that matter to the way you will actually use it.',proofSpeech(proofs()),materialLine(),summaryLine(),chosenClose('What, if anything, do you still need answered about charging, range or ownership before this becomes a real option?'),closeSilence()]);},shots:[['0–8s','Exact vehicle','Identify trim/drivetrain accurately.'],['8–24s','Charging / fuel-system proof','Port/connector or hybrid-specific interface when relevant.'],['24–40s','Verified range / efficiency','Use verified information only.'],['40–56s','Cabin / controls','The ownership tech they will use.'],['56–70s','Cargo / packaging','Show any space impact that matters.'],['70–82s','Ownership question','Surface the remaining ownership uncertainty.']],avoid:['Do not overload the customer with EV terminology. Use their routine and words.','When they name the real ownership concern, stay on it until it is solved.','Do not let confidence in the product become a substitute for a verified range/incentive fact.']},
compare:{title:'Comparable / alternative vehicle',length:'50–75 sec',goal:'Test the acceptable difference',objective:'Name the meaningful difference early, prove the shared buying reason and determine whether the compromise is acceptable.',script:function(){var diff=condition()?'The meaningful difference is '+condition()+'.':'This is not the exact vehicle you first asked about, so I want to call that out first.';return script([intro(),diff,focusLine(),proofSpeech(proofs()),summaryLine(),chosenClose('If this solves the reason you wanted the original vehicle, what else would still have to be right before you would consider it?'),closeSilence()]);},shots:[['0–8s','Name the difference','Do not make the customer discover the mismatch halfway through the video.'],['8–24s','Prove the shared need','Show the reason the alternative deserves consideration.'],['24–40s','Show the actual difference','Color, trim, year, equipment or condition.'],['40–56s','Supporting proof','Only details that help judge the trade-off.'],['56–70s','Decision question','Ask whether the difference is acceptable.']],avoid:['Do not call an alternative identical when it is not.','Use the customer’s original must-have as the anchor; do not sell random inventory.','If the difference is a hard line, stop pushing that alternative and reset the search.']}
};
function current(){return DATA[situ()]||DATA.first;}
function focal(){var p=cleanPhrase(phrase());if(p)return p;if(need())return need();if(concern())return concern();if(condition())return condition();return 'the part that matters most to your decision';}
function subjectLine(){var s=situ();if(s==='price')return car()+' — the comparison that matters';if(s==='used'||s==='damage')return car()+' — condition video';if(s==='remote')return car()+' — proof before the trip';if(s==='feature')return car()+' — the item you asked about';if(s==='compare')return car()+' — the meaningful difference';return car()+' — quick video';}
function echoCompanion(){var p=cleanPhrase(phrase());return p?'I focused on “'+p+'” because that was the way you described what matters.':'I focused on '+focal()+'.';}
function sms(){var s=situ();if(s==='price')return 'Hi '+name()+', Aldrin at Sheehy Nissan. I sent the video on the '+car()+'. '+echoCompanion()+' If you have the other listing or offer, send it over and I’ll compare the meaningful differences.';if(s==='used'||s==='damage')return 'Hi '+name()+', Aldrin at Sheehy Nissan. I sent the condition video on the '+car()+'. '+echoCompanion()+' Based on what I showed you, does the condition work for you?';if(s==='remote')return 'Hi '+name()+', Aldrin at Sheehy Nissan. I sent a more complete video of the actual '+car()+'. '+echoCompanion()+' If the vehicle checks out, we can structure the deal before you travel.';if(s==='feature')return 'Hi '+name()+', Aldrin at Sheehy Nissan. I sent the video on the actual '+car()+' focused on '+(concern()||focal())+'. Does that answer it, or is there one more must-have I should verify?';if(s==='compare')return 'Hi '+name()+', Aldrin at Sheehy Nissan. I sent the comparable '+car()+' video and called out the meaningful difference. Does that difference work for you, or is it a hard line?';return 'Hi '+name()+', Aldrin at Sheehy Nissan. I sent the actual '+car()+' video. '+echoCompanion()+' Does that look like the right direction?';}
function email(){var s=situ(),body='Hi '+name()+',\n\n';if(s==='price')body+='I sent the DriveCentric video on the actual '+car()+'. '+echoCompanion()+'\n\nIf you have the competing listing, stock number or written offer, send it over and I’ll compare the parts that actually affect the deal.';else if(s==='used'||s==='damage')body+='I sent the condition video on the actual '+car()+'. '+echoCompanion()+'\n\nBased on what I showed you, does the condition work for you?';else if(s==='remote')body+='I sent a more complete video of the actual '+car()+' because I want the big questions answered before you travel. '+echoCompanion()+'\n\nIf the vehicle checks out, the next step is to structure the deal so you know where you stand before making the trip.';else if(s==='feature')body+='I sent the video on the actual '+car()+' and went straight to '+(concern()||focal())+'.\n\nDoes that answer it, or is there one more must-have you want me to verify?';else if(s==='compare')body+='I sent the comparable '+car()+' video and called out the meaningful difference first.\n\nIf it solves the reason you wanted the original, what else would still have to be right before you would consider it?';else body+='I sent a short video of the actual '+car()+'. '+echoCompanion()+'\n\nDoes that look like the right direction? If it does, I have '+t1()+' or '+t2()+' available.';return {subject:subjectLine(),body:body};}
function voicemail(){var s=situ(),base='Hi '+name()+', this is Aldrin at Sheehy Nissan. ';if(s==='remote')return base+'I sent you a proof video of the actual '+car()+' before you make the trip. Take a look and call me at '+phone()+'.';if(s==='price')return base+'I sent the '+car()+' video so we can compare the right vehicle. If you have the other offer, send it over or call me at '+phone()+'.';if(s==='used'||s==='damage')return base+'I sent the condition video on the '+car()+', including the area you asked about. Take a look and call me at '+phone()+'.';if(s==='feature')return base+'I sent the video on the '+car()+' showing the item you asked about. Take a look and call me at '+phone()+'.';return base+'I sent you a short video of the actual '+car()+'. Take a look and call me at '+phone()+'.';}
function defaultCloseFor(s){if(s==='used'||s==='damage')return 'condition';if(s==='remote')return 'remote';if(s==='price')return 'comparison';if(s==='feature'||s==='ev')return 'answer';return 'appointment';}
function crm(){var p=proofs(),cta=val('nextCommitment')==='auto'?defaultCloseFor(situ()):val('nextCommitment');return 'DriveCentric video sent on '+car()+'. Situation: '+current().title+'. Customer language: '+(cleanPhrase(phrase())||'not captured')+'. Focus: '+focal()+'.'+(p.length?' Proof shown: '+p.join('; ')+'.':'')+(condition()?' Material condition/difference: '+condition()+'.':'')+' CTA: '+cta+'.';}
function shotHtml(x){return '<div class="shot"><div class="shot-time">'+esc(x[0])+'</div><div><b>'+esc(x[1])+'</b><span>'+esc(x[2])+'</span></div></div>';}
function avoidHtml(x){return '<div class="avoid-line"><b>Use:</b> '+esc(x)+'</div>';}
function fallback(text){var ta=document.createElement('textarea');ta.value=text;ta.style.position='fixed';ta.style.opacity='0';document.body.appendChild(ta);ta.select();try{document.execCommand('copy');}catch(e){}ta.remove();}
function copied(btn){var old=btn.textContent;btn.textContent='Copied';setTimeout(function(){btn.textContent=old;},850);var t=$('toast');t.classList.add('show');setTimeout(function(){t.classList.remove('show');},700);}
function copyText(text,btn){if(navigator.clipboard&&navigator.clipboard.writeText)navigator.clipboard.writeText(text).then(function(){copied(btn);}).catch(function(){fallback(text);copied(btn);});else{fallback(text);copied(btn);}}
function channelCard(nameText,meta,text,subject){var id='c_'+Math.random().toString(36).slice(2),sub=subject?'<span class="subject">Subject: '+esc(subject)+'</span>':'';return '<div class="channel"><div class="channel-head"><div><div class="channel-name">'+esc(nameText)+'</div><div class="channel-meta">'+esc(meta)+'</div></div><button class="copy" type="button" data-copy="'+id+'">Copy</button></div><div class="channel-body" id="'+id+'">'+sub+esc(text)+'</div></div>';}
function renderChannels(){var em=email();$('channels').innerHTML=channelCard('SMS','One job · one question',sms())+channelCard('Email','No manual signature',em.body,em.subject)+channelCard('Voicemail','Short callback reason',voicemail())+channelCard('CRM note','Factual record',crm());document.querySelectorAll('[data-copy]').forEach(function(b){b.onclick=function(){var el=$(b.getAttribute('data-copy'));copyText(el.innerText||el.textContent||'',b);};});}
function gapLoop(){var g=certaintyGap();if(!g||g.n>=8)return 'If they give you a real answer, take the next commitment. Do not reopen discovery.';if(g.k==='vehicle')return 'Vehicle certainty is lowest. Ask what about the vehicle itself is still not fully there, prove that point and re-close.';if(g.k==='you')return 'Trust in you is lowest. Slow down, answer the exact concern, use their words and make the next promise small and specific.';return 'Store/process certainty is lowest. Ask what about doing business with us or the process still makes them hesitate. Solve that one issue and re-close.';}
var REPLIES={
good:{label:'Looks good',line:function(){return situ()==='remote'?'Good. Then let’s structure the deal before you travel. Are you planning to finance it or pay cash?':'Good. Then let’s put a time on it. I have '+t1()+' or '+t2()+'. Which works better?';},after:function(){return 'Positive answer = advance. '+gapLoop();}},
price:{label:'Price problem',line:function(){return 'It sounds like the number is the part that still has to make sense. Compared with what - another exact vehicle, a written offer, or a target you have in mind?';},after:function(){return 'Listen. Mirror one meaningful phrase from the answer, then ask: “Other than price, what else would stop you?”\n'+gapLoop();}},
condition:{label:'Condition concern',line:function(){return 'It sounds like the condition is the hold-up. Which exact area changes the decision for you?';},after:function(){return 'Do not defend the vehicle. Get the exact condition issue first, show/verify it, then ask whether anything else remains.\n'+gapLoop();}},
feature:{label:'Missing feature',line:function(){return 'Which feature is the hard line for you?';},after:function(){return 'Echo their feature wording once. Verify the exact unit. If it does not have the must-have, change the vehicle rather than arguing the requirement.';}},
think:{label:'Needs to think',line:function(){return 'It sounds like something is still unsettled. What specifically do you need to get comfortable with before this becomes a yes or no?';},after:function(){return 'Stay quiet after the question. When they answer, summarize the issue back and loop the weakest certainty. '+gapLoop();}},
compare:{label:'Comparing another car',line:function(){return 'What is the other option doing better for you right now - price, equipment, condition, trade, convenience, or something else?';},after:function(){return 'Get the actual listing/offer. Ask how they are comparing the two. Do not negotiate against an undefined competitor.\n'+gapLoop();}},
decision:{label:'Other decision-maker',line:function(){return 'What does the other person need to see or hear before they would be comfortable moving forward?';},after:function(){return 'Do not make the customer relay your pitch. Get everyone on the same information when possible, then isolate what would still hold this customer back.';}},
more:{label:'Wants more info',line:function(){return 'Absolutely. What is the one detail that could actually change your decision?';},after:function(){return 'Answer that detail first. More information is not the goal; the next decision is.';}},
noresponse:{label:'No response',line:function(){return 'I sent the video focused on '+focal()+'. What, if anything, is still missing?';},after:function(){return 'Do not ask “Did you watch it?” Reconnect the video to their stated reason and make the reply easy.';}}
};
var activeReply='good';
function renderReplies(){$('replyButtons').innerHTML=Object.keys(REPLIES).map(function(k){return '<button type="button" data-reply="'+k+'" class="'+(k===activeReply?'on':'')+'">'+esc(REPLIES[k].label)+'</button>';}).join('');var r=REPLIES[activeReply]||REPLIES.good;$('nextLine').textContent=r.line();$('nextAfter').textContent=typeof r.after==='function'?r.after():r.after;document.querySelectorAll('[data-reply]').forEach(function(b){b.onclick=function(){activeReply=b.getAttribute('data-reply');renderReplies();};});}
function renderMissing(){var x=[];if(!val('vehicle'))x.push('Add the exact vehicle.');if(!phrase()&&!need()&&!concern()&&situ()!=='used'&&situ()!=='damage')x.push('Add the customer’s exact phrase, priority or question so the video has a real reason to exist.');if((situ()==='damage'||situ()==='used')&&!condition()&&!concern())x.push('Add the condition point you inspected.');if(situ()==='price'&&!comparison())x.push('If you know the competing vehicle or offer, add it; otherwise the script will ask for it.');var el=$('missing');if(x.length){el.textContent=x.join(' ');el.classList.add('show');}else{el.textContent='';el.classList.remove('show');}}
function renderCertainty(){$('certaintyTarget').textContent=certaintyTarget();$('languageTarget').textContent=languageTarget();$('deliveryTarget').textContent=deliveryText();var h=$('certaintyHint');if(h)h.textContent=certaintyInstruction();}
function render(){var d=current();$('situationTitle').textContent=d.title;$('lengthBadge').textContent=d.length;$('goalBadge').textContent=d.goal;$('objectiveText').textContent=d.objective;$('spokenScript').textContent=d.script();$('shotList').innerHTML=d.shots.map(shotHtml).join('');$('avoidList').innerHTML=d.avoid.map(avoidHtml).join('');renderCertainty();renderChannels();renderReplies();renderMissing();}
function seedScores(){['certaintyVehicle','certaintyYou','certaintyStore'].forEach(function(id){var e=$(id);if(e&&!e.options.length)e.innerHTML=scoreOptions();});}
function bind(){seedScores();['clientName','vehicle','customerPhrase','situation','customerNeed','concern','useCase','proof1','proof2','proof3','condition','comparison','travel','certaintyVehicle','certaintyYou','certaintyStore','deliveryStyle','nextCommitment','timeOne','timeTwo'].forEach(function(id){var e=$(id);if(!e)return;e.addEventListener('input',render);e.addEventListener('change',render);});$('refreshBtn').onclick=render;$('clearVideo').onclick=function(){['concern','useCase','proof1','proof2','proof3','condition','comparison','travel'].forEach(function(id){$(id).value='';});$('nextCommitment').value='auto';render();};setTimeout(render,100);}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',bind);else bind();
})();
